---
title: "PathoStat package Introduction"
author: "Solaiappan Manimaran"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PathoStatIntro}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
The purpose of this package is to perform Statistical Analysis on the 
PathoScope generated reports file.

The package includes:

1. Relative Abundance plots

`runPathoStat` is the pipeline function that generates the PathoStat report
and launches shiny app when in interactive mode. It combines all the functions 
into one step.

## Installation

To begin, install [Bioconductor](http://www.bioconductor.org/) along with a
few dependencies that PathoStat uses:

```r
source("http://bioconductor.org/biocLite.R")
biocLite(c('phyloseq', 'pander', 'MCMCpack', 'limma', 'preprocessCore', 
'stringi', 'corpcor', 'matrixStats', 'shiny', 'ggvis', 'd3heatmap', 'reshape2',
'scales', 'rentrez', 'devtools'))
```
Install 'pandoc' package by following the instructions at the following URL:
http://pandoc.org/installing.html

Rstudio also provides pandoc binaries at the following location for Windows, 
Linux and Mac:
https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.13.1.zip 

Next, use [devtools](https://github.com/hadley/devtools) to install the latest
version of PathoStat from Github:
```r
require(devtools)
install_github("mani2012/PathoStat", build_vignettes=TRUE, auth_token="dadf36cdaef71a2f761f193862a8f6f3f36e3966")
```

If all went well you should now be able to load PathoStat. 
Here is an example use of the pipeline.

### Example batch and condition
```r
nbatch <- 11
ncond <- 3
npercond <- 11
subject_id <- c(1, 1, 1, 2, 2, 2, 3, 3, 3, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 
    10, 10, 10, 12, 12, 12, 13, 13, 13, 15, 15, 15)
batch <- unlist(lapply(subject_id, FUN=function(id) {paste("Person", id)}))
diet <- c(1, 3, 2, 3, 1, 2, 2, 3, 1, 3, 2, 1, 3, 2, 1, 3, 1, 2, 1, 2, 3, 
    2, 1, 3, 3, 1, 2, 3, 1, 2, 2, 3, 1)
diet_key <- c("simple", "refined", "unrefined")
condition <- diet_key[diet]
```

### Example 1: Apply PathoStat
```r
example_data_dir <- system.file("example/data", package = "PathoStat")
runPathoStat(input_dir=example_data_dir, batch=batch, condition=condition, 
    report_file="pathostat_report.html", report_dir=".", report_option_binary=
    "111111111", view_report=FALSE, interactive=TRUE)
```

### Example 2: L1 set
```r
example2_data_dir <- system.file("example/data2/L1", package = "PathoStat")
runPathoStat(input_dir=example2_data_dir, batch=batch, condition=condition, 
    report_file="pathostat_report.html", report_dir=".", report_option_binary=
    "111111111", view_report=FALSE, interactive=TRUE)
```
### Example 2: L2 set
```r
example2_data_dir <- system.file("example/data2/L2", package = "PathoStat")
runPathoStat(input_dir=example2_data_dir, batch=batch, condition=condition, 
    report_file="pathostat_report.html", report_dir=".", report_option_binary=
    "111111111", view_report=FALSE, interactive=TRUE)
```
